-- EMPLOYEES (scott 계정의 EMP 테이블 원본)
-- EMPLOYEES 전체 조회
SELECT * FROM  EMPLOYEES e ;
-- EMPLOYEES 의 first_name, last_name, job_id 조회
SELECT
	FIRST_NAME,
	LAST_NAME,
	JOB_ID
FROM
	EMPLOYEES e ;

-- 사원번호가 176인 사원의 LAST_NAME, 부서번호 조회
SELECT LAST_NAME , DEPARTMENT_ID 
FROM EMPLOYEES e
WHERE EMPLOYEE_ID = 176;

-- 급여 12000 이상 되는 직원들의 LAST_NAME과 급여 조회
SELECT LAST_NAME, SALARY 
FROM EMPLOYEES e
WHERE SALARY >= 12000;

-- 급여가 5000에서 12000범위가 아닌 사람들의 LAST_NAME과 급여 조회
SELECT LAST_NAME, SALARY 
FROM EMPLOYEES e
WHERE SALARY > 12000
OR SALARY < 5000;

-- 20번 혹은 50번 부서에서 근무하는 사원들의 LAST_NAME, 부서번호를 조회
-- 단 이름 오름차순, 부서 오름차순 정렬
SELECT LAST_NAME, DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID 
IN (20, 50);

-- 커미션을 버는 사원들의 LAST_NAME, SALARY, COMMISSION_PCT 조회
-- 단 연봉의 내림차순, 커미션 내림차순으로 정렬
SELECT LAST_NAME, SALARY, COMMISSION_PCT 
FROM EMPLOYEES e
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC, COMMISSION_PCT DESC;

-- 연봉이 2500, 3500, 7000이 아니며 JOB_ID가 SA_REP 또는 ST_CLERK인 사원 조회
SELECT *
FROM EMPLOYEES e 
WHERE SALARY NOT IN(2500, 3500, 7000)
AND JOB_ID IN('SA_REP', 'ST_CLERK');

-- 2018/02/20 ~ 2018/05/01 사이에 고용된 직원들의 LAST_NAME, EMPLOYEE_ID, HIRE_DATE 조회
SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE 
FROM EMPLOYEES e 
WHERE HIRE_DATE >= '2018-02-20'
AND HIRE_DATE <= '2018-05-01';

-- 2015년에 고용된 사원 조회
SELECT *
FROM EMPLOYEES e 
WHERE HIRE_DATE >= '2015-01-01'
AND HIRE_DATE <= '2015-12-31';

-- BETWEEN A AND B
-- 20번 혹은 50번 부서에서 근무하며, 연봉이 5000~12000 사이인 직원들의
-- FIRST_NAME, LAST_NAME, 연봉 조회(연봉 오름차순)
SELECT FIRST_NAME , LAST_NAME , SALARY 
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID IN(20, 50)
AND SALARY BETWEEN 5000 AND 12000
ORDER BY SALARY ASC;

-- 연봉이 5000~12000가 아닌 직원 정보조회
SELECT *
FROM EMPLOYEES e 
WHERE SALARY NOT BETWEEN 5000 AND 12000;

-- 2018/02/20 ~ 2018/05/01 사이에 고용된 직원들의 LAST_NAME, EMPLOYEE_ID, HIRE_DATE 조회
SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE 
FROM EMPLOYEES e 
WHERE HIRE_DATE BETWEEN '2018-02-20' AND '2018-05-01';

-- LIKE
-- LAST_NAME에 u가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%u%';

-- LAST_NAME의 네번째 글자가 a인 사원들의 사번, LAST_NAME 조회
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '___a%';

-- LAST_NAME에 a 혹은 e 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단 LAST_NAME 오름차순)
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME;

-- LAST_NAME에 a 와 e 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단 LAST_NAME 오름차순)
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME;

-- IS NULL
-- MANAGER_ID가 없는 사원들의 LAST_NAME, JOB_ID 조회
SELECT LAST_NAME , JOB_ID 
FROM EMPLOYEES e 
WHERE MANAGER_ID IS NULL;

-- JOB_ID가 ST_CLERK인 부서 조회
-- 단, 부서번호가 NULL인 경우는 제외
SELECT DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE JOB_ID IN ('ST_CLERK')
AND DEPARTMENT_ID IS NOT NULL;

-- COMMISSION_PCT가 NULL이 아닌 사원 중 COMMISSION = SALARY * COMMISSION_PCT를 구함
-- 사원번호, FIRST_NAME, JOB_ID 와 함께 조회
SELECT EMPLOYEE_ID , FIRST_NAME , JOB_ID , SALARY*COMMISSION_PCT AS "COMMISSION"
FROM EMPLOYEES e 
WHERE COMMISSION_PCT IS NOT NULL;

-- 부서 80의 사원에 적용 가능한 세율 표시
-- LAST_NAME, SALARY, TAX_RATE
-- TAX_RATE는 SALARY/2000 으로 나눈 후 버림
-- 해당 값이 0이면 0.0 / 1, 0.09 / 2, 0.20 / 3, 0.30 / 4, 0.40 / 5, 0.42 / 6, 0.44 / 그 외 0.45
SELECT LAST_NAME , SALARY ,
	CASE TRUNC(SALARY/2000)
		WHEN 0 THEN 0.0
		WHEN 1 THEN 0.09
		WHEN 2 THEN 0.20
		WHEN 3 THEN 0.30
		WHEN 4 THEN 0.40
		WHEN 5 THEN 0.42
		WHEN 6 THEN 0.44
		ELSE 0.45
	END AS TAX_RATE
FROM EMPLOYEES e
WHERE DEPARTMENT_ID = 80; 


-- 회사 내의 최대 연봉 및 최소 연봉의 차이를 출력
SELECT (MAX(SALARY)-MIN(SALARY)) AS "연봉 차이"
FROM EMPLOYEES e ;

-- 매니저로 근무하는 사원들의 총 숫자를 출력
SELECT COUNT(DISTINCT(MANAGER_ID))
FROM EMPLOYEES e ;

-- 각 매니저가 관리하는 급여가 6000 이상인 사원들 중에서 최소 급여 조회 
SELECT MANAGER_ID , MIN(SALARY)
FROM EMPLOYEES e 
GROUP BY MANAGER_ID 
HAVING MANAGER_ID IS NOT NULL AND MIN(SALARY) >= 6000
ORDER BY MANAGER_ID ;















